In [1]:
import numpy as np
import pandas as pd
import seaborn as sb
sb.set()
import matplotlib.pyplot as mpl
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression

In [2]:
data=pd.read_csv("1.02. Multiple linear regression.csv")
x=data[['SAT','Rand 1,2,3']]
y=data['GPA']

In [3]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [5]:
pvalue=f_regression(x,y)[1]
pvalue

array([7.19951844e-11, 6.76291372e-01])

In [7]:
pvalue.round(3)

array([0.   , 0.676])